// Mirrors the pipeline's DocType union (server/src/pipeline/schema.ts) as labels for the UI.
export type DocumentKind =
  | 'Site plan'
  | 'Wiring layout'
  | 'Switchboard schedule'
  | 'Single line diagram'
  | 'Legend'
  | 'COC'
  | 'ESC'
  | 'Quote'
  | 'Invoice'
  | 'Cable schedule'
  | 'Spreadsheet'
  | 'Other'

export type DocumentStatus = 'pending' | 'extracted' | 'needs_review' | 'skipped_all_noise' | 'error'

export interface JobDocument {
  id: string
  projectId: string
  fileName: string
  kind: DocumentKind
  status: DocumentStatus
  pageCount?: number
  sizeLabel?: string
  uploadedBy: string
  /** Display format used by the rest of the app, e.g. "Sep 14, 2026". */
  uploadedAt: string
  needsReviewCount?: number
  summary: string
  /** Full pipeline extraction JSON - only present on the single-document detail fetch. */
  extracted?: unknown
  /** Optional real page image - not generated by this pipeline, always undefined for now. */
  previewUrl?: string
}

export const STATUS_LABEL: Record<DocumentStatus, string> = {
  pending: 'Processing',
  extracted: 'Extracted',
  needs_review: 'Needs review',
  skipped_all_noise: 'All noise',
  error: 'Error',
}

export const STATUS_STYLE: Record<DocumentStatus, string> = {
  pending: 'text-black/50',
  extracted: 'text-[#1a7a3d]',
  needs_review: 'text-[#a16207]',
  skipped_all_noise: 'text-black/50',
  error: 'text-[#E3350D]',
}

const KIND_BY_DOC_TYPE: Record<string, DocumentKind> = {
  site_plan: 'Site plan',
  wiring_layout_plan: 'Wiring layout',
  switchboard_schedule: 'Switchboard schedule',
  single_line_diagram: 'Single line diagram',
  legend: 'Legend',
  coc: 'COC',
  esc: 'ESC',
  quote: 'Quote',
  invoice: 'Invoice',
  cable_schedule: 'Cable schedule',
  spreadsheet_export: 'Spreadsheet',
  other_noise: 'Other',
}

/** The subset of the pipeline's extraction output the UI reads. */
interface ExtractionOutput {
  doc_type?: string
  pages_total?: number | null
  legend_items?: unknown[]
  circuits?: unknown[]
  switchboards?: unknown[]
  single_line_elements?: unknown[]
  compliance_records?: unknown[]
  financial_line_items?: unknown[]
  cable_schedule_rows?: unknown[]
  needs_review?: unknown[]
}

type ExtractionCollection = Exclude<keyof ExtractionOutput, 'doc_type' | 'pages_total'>

const COLLECTION_NOUNS: [ExtractionCollection, string][] = [
  ['circuits', 'circuit'],
  ['switchboards', 'switchboard'],
  ['single_line_elements', 'single-line element'],
  ['compliance_records', 'compliance record'],
  ['financial_line_items', 'line item'],
  ['cable_schedule_rows', 'cable run'],
  ['legend_items', 'legend item'],
]

function summariseExtraction(extracted: unknown): string {
  if (!extracted || typeof extracted !== 'object') return ''
  const doc = extracted as ExtractionOutput

  const parts: string[] = []
  for (const [key, noun] of COLLECTION_NOUNS) {
    const count = doc[key]?.length ?? 0
    if (count > 0) parts.push(`${count} ${noun}${count === 1 ? '' : 's'}`)
  }
  const needsReview = doc.needs_review?.length ?? 0
  if (needsReview > 0) parts.push(`${needsReview} needing review`)
  return parts.join(' · ')
}

export function fileExtension(fileName: string): string {
  const dot = fileName.lastIndexOf('.')
  return dot === -1 ? 'FILE' : fileName.slice(dot + 1).toUpperCase()
}

// Matches the display format the UI has always used, e.g. "Sep 14, 2026".
function formatDate(iso: string): string {
  return new Date(iso).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })
}

function toStatus(row: { status: string; needs_review_count: number }): DocumentStatus {
  if (row.status === 'extracted' && row.needs_review_count > 0) return 'needs_review'
  if (row.status === 'skipped_noise') return 'skipped_all_noise'
  return row.status as DocumentStatus
}

interface DocumentListRow {
  id: string
  source_file: string
  doc_type: string | null
  status: string
  needs_review_count: number
  created_at: string
  pages_total: number | null
}

function toJobDocumentFromList(row: DocumentListRow, projectId: string): JobDocument {
  return {
    id: row.id,
    projectId,
    fileName: row.source_file,
    kind: (row.doc_type ? KIND_BY_DOC_TYPE[row.doc_type] : undefined) ?? 'Other',
    status: toStatus(row),
    pageCount: row.pages_total ?? undefined,
    uploadedBy: 'You',
    uploadedAt: formatDate(row.created_at),
    needsReviewCount: row.needs_review_count,
    summary: row.status === 'skipped_noise' ? 'No relevant pages found in this file.' : '',
  }
}

export async function getDocumentsForProject(projectId: string): Promise<JobDocument[]> {
  const res = await fetch(`/api/projects/${projectId}/documents`)
  const body = await res.json()
  if (!res.ok) throw new Error(body?.error ?? `request failed (${res.status})`)
  return (body.documents as DocumentListRow[]).map((row) => toJobDocumentFromList(row, projectId))
}

interface DocumentDetailRow {
  id: string
  project_id: string
  source_file: string
  doc_type: string | null
  status: string
  needs_review_count: number
  error: string | null
  extraction: ExtractionOutput | null
  created_at: string
}

export async function getDocumentById(documentId: string): Promise<JobDocument | null> {
  const res = await fetch(`/api/documents/${documentId}`)
  if (res.status === 404) return null
  const body = await res.json()
  if (!res.ok) throw new Error(body?.error ?? `request failed (${res.status})`)
  const row = body.document as DocumentDetailRow

  return {
    id: row.id,
    projectId: row.project_id,
    fileName: row.source_file,
    kind: (row.doc_type ? KIND_BY_DOC_TYPE[row.doc_type] : undefined) ?? 'Other',
    status: toStatus(row),
    pageCount: row.extraction?.pages_total ?? undefined,
    uploadedBy: 'You',
    uploadedAt: formatDate(row.created_at),
    needsReviewCount: row.needs_review_count,
    summary: row.error
      ? row.error
      : summariseExtraction(row.extraction) ||
        (row.status === 'skipped_noise' ? 'No relevant pages found in this file.' : ''),
    extracted: row.extraction ?? undefined,
  }
}
